import { expect, test } from '@playwright/test'
import { SESSION_STORAGE_KEY } from '../src/utils/sessionStorage.ts'
import { completeExploration } from './exploration.ts'

test.beforeEach(async ({ page }) => {
  await page.goto('/denge-kasabasi/oyna/')
  await page.getByRole('button', { name: 'GÖREVE BAŞLA' }).click()
  await expect(page.getByRole('heading', { name: 'İlk Görevin', exact: true })).toBeFocused()
})

test('opening and dismissing do not complete an area; completion persists once', async ({ page }) => {
  const progress = page.getByRole('status', { name: 'Görev ilerlemesi' })
  const cta = page.getByRole('button', { name: 'ÇÖZÜMLERİ İNCELE' })
  const dam = page.getByRole('button', { name: /^Baraj:/ })
  await expect(page.getByLabel('Başlangıç kaynakları')).toContainText('Su: %42')
  await expect(page.getByLabel('Başlangıç kaynakları')).toContainText('Bütçe: 50')
  await expect(page.locator('.location-checklist')).toHaveCount(0)
  await expect(cta).toBeDisabled()
  await dam.click()
  const modal = page.getByRole('dialog', { name: 'Baraj' })
  await expect(modal).toContainText('Murat')
  await expect(modal).toContainText('Su Mühendisi')
  await expect(modal).toContainText('Su sınırlı bir kaynaktır.')
  await page.keyboard.press('Escape')
  await expect(modal).toHaveCount(0)
  await expect(dam).toBeFocused()
  await expect(progress).toHaveText('0/5 Bölge İncelendi')
  await dam.click()
  await page.getByRole('button', { name: 'Bilgi kartını kapat' }).click()
  await expect(progress).toHaveText('0/5 Bölge İncelendi')
  await dam.click()
  await page.mouse.click(2, 2)
  await expect(modal).toHaveCount(0)
  await expect(progress).toHaveText('0/5 Bölge İncelendi')
  await dam.click()
  await page.getByRole('button', { name: 'İNCELEMEYİ TAMAMLA' }).click()
  await expect(progress).toHaveText('1/5 Bölge İncelendi')
  await expect(dam).toHaveAccessibleName(/incelendi/)
  await expect(dam).toContainText('✓')
  await dam.click()
  await page.getByRole('button', { name: 'İNCELEMEYİ TAMAMLA' }).click()
  await page.reload()
  await expect(progress).toHaveText('1/5 Bölge İncelendi')
  const stored = await page.evaluate((key) => JSON.parse(localStorage.getItem(key)!), SESSION_STORAGE_KEY)
  expect(stored.state.exploredLocations).toEqual(['dam'])
  expect(stored.state.events.filter((event: { eventType: string }) => event.eventType === 'location_opened')).toHaveLength(1)
  await expect(cta).toBeDisabled()
})

test('all five completions unlock the existing research screen', async ({ page }) => {
  await completeExploration(page)
  await expect(page.getByRole('region', { name: 'Lina' })).toContainText('Harika! Kasabanın tüm bölgelerini inceledin.')
  await expect(page.getByRole('progressbar')).toHaveAttribute('value', '5')
  await page.getByRole('button', { name: 'ÇÖZÜMLERİ İNCELE' }).click()
  await expect(page.getByRole('button', { name: 'PLAN OLUŞTURMAYA GEÇ' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: 'PLAN OLUŞTURMAYA GEÇ' })).toBeVisible()
})

for (const width of [1440, 375]) {
  test(`all area cards are readable and keyboard accessible at ${width}px`, async ({ page }, testInfo) => {
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    await page.setViewportSize({ width, height: 800 })
    await page.screenshot({ path: testInfo.outputPath('task.png'), fullPage: true })
    for (const [name, character] of [['Baraj', 'Murat'], ['Evler', 'Elif'], ['Tarım', 'Hasan'], ['Park', 'Zeynep'], ['Belediye', 'Derya']]) {
      const trigger = page.getByRole('button', { name: new RegExp(`^${name}:`) })
      await trigger.focus()
      await page.keyboard.press('Enter')
      const modal = page.getByRole('dialog', { name, exact: true })
      await expect(modal).toContainText(character)
      await expect(page.getByRole('button', { name: 'Bilgi kartını kapat' })).toBeFocused()
      await page.keyboard.press('Shift+Tab')
      await expect(page.getByRole('button', { name: 'İNCELEMEYİ TAMAMLA' })).toBeFocused()
      await page.keyboard.press('Tab')
      await expect(page.getByRole('button', { name: 'Bilgi kartını kapat' })).toBeFocused()
      expect(await modal.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      if (name === 'Baraj') await page.screenshot({ path: testInfo.outputPath('dam-popup.png'), fullPage: true })
      await page.getByRole('button', { name: 'İNCELEMEYİ TAMAMLA' }).click()
      await expect(trigger).toBeFocused()
    }
    expect(errors).toEqual([])
  })
}
